add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
disabled = true

[directory]
truncation_length = 1

[line_break]
disabled = true

[python]
disabled = true
