"Basic Config
set number
set relativenumber
syntax on
colorscheme wal
set wrap linebreak nolist
set laststatus=2

"Change location of viminfo
set viminfofile=$HOME/.vim/viminfo

"Setup Tabs
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set autoindent
set smartindent

"Settingup filetype for autocommands
filetype plugin on
filetype detect
filetype indent on

"Seting Folds (mostly for python)
set foldlevel=20
set fillchars=fold:\ 
function! FoldMethod(lnum)
    let l:indent = max([indent(a:lnum+1), indent(a:lnum)])
    return l:indent / &shiftwidth
endfunction
set foldmethod=expr
set foldexpr=FoldMethod(v:lnum)

"Searching highlights everything, space to remove highlight
set incsearch hlsearch
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

"LaTeX Autocommands
" Sa - Start new Article
" Sb - Start new Beamer
" b - Bold
" i - Italic
" u - Underline
" P - First time paragraph citation
" p - Paragraph citation
" 1 - New Section
" 2 - New subsection
" 3 - New subsubsection
" fr - New Beamer frame
" Fg - First time new image with caption
" fg - New image with caption
" E - First time numbered list
" e - Numbered list
" L - First time bullet list
" l - Bullet list
" I - New list item
let g:tex_flavor = "latex"
autocmd FileType tex inoremap ;; <Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;Sa \documentclass[10pt,letterpaper]{article}<Enter><Enter>\edef\restoreparindent{\parindent=\the\parindent\relax}<Enter>\usepackage{parskip}<Enter>\restoreparindent<Enter>\usepackage[margin=1in]{geometry}<Enter>\usepackage{titlesec}<Enter>\titleformat{\section}{\LARGE\bfseries}{}{0em}{}<Enter><Enter>\title{<++>}<Enter>\author{Michael D. Allred}<Enter><Enter>\begin{document}<Enter><Enter>\maketitle<Enter><Enter>\section{<++>}<Enter><Enter><++><Enter><Enter>\end{document}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;Sb \documentclass[aspectratio=169]{beamer}<Enter><Enter>\title{<++>}<Enter>\author{Michael<Space>D.<Space>Allred}<Enter><Enter>\usetheme{Berkeley}<Enter><Enter>\begin{document}<Enter><Enter>\maketitle<Enter><Enter><++><Enter><Enter>\end{document}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;b \textbf{}<Space><++><Esc>F}i
autocmd FileType tex inoremap ;i \textit{}<Space><++><Esc>F}i
autocmd FileType tex inoremap ;u \underline{}<Space><++><Esc>F}i
autocmd FileType tex inoremap ;p \parencite{}.<Space><++><Esc>F}i
autocmd FileType tex inoremap ;P \parencite{<++>}.<Space><++><Esc>?usepackage<Enter>o\usepackage[backend=biber,style=apa,autocite=inline]{biblatex}<Enter>\addbibresource{<++>}<Esc>/end{document}<Enter>O<Enter>\printbibliography<Enter><Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;1 <Enter>\section{<++>}<Enter><Enter><++><Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;2 <Enter>\subsection{<++>}<Enter><Enter><++><Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;3 <Enter>\subsubsection{<++>}<Enter><Enter><++><Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;fr \begin{frame}<Enter>\frametitle{}<Enter><++><Enter>\end{frame}<Esc>kkf}i
autocmd FileType tex inoremap ;fg \begin{figure}[H]<Enter>\centering<Enter>\includegraphics[width=<++>\textwidth]{<++>}<Enter>\caption{<++>\label{<++>}}<Enter>\end{figure}<Enter><++><Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;Fg \begin{figure}[H]<Enter>\centering<Enter>\includegraphics[width=<++>\textwidth]{<++>}<Enter>\caption{<++>\label{<++>}}<Enter>\end{figure}<Enter><++><Esc>?usepackage<Enter>o\usepackage{graphicx}<Enter>\usepackage{float}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;e \begin{enumerate}[noitemsep]<Enter>\item<Space><++><Enter>\end{enumerate}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;E \begin{enumerate}[noitemsep]<Enter>\item<Space><++><Enter>\end{enumerate}<Esc>/usepackage<Enter>o\usepackage{enumitem}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;l \begin{itemize}[noitemsep]<Enter>\item<Space><++><Enter>\end{itemize}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;L \begin{itemize}[noitemsep]<Enter>\item<Space><++><Enter>\end{itemize}<Esc>/usepackage<Enter>o\usepackage{enumitem}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;I \item<Space>
autocmd FileType tex inoremap ;c \begin{multicols}{<++>}<Enter><++><Enter>\end{multicols}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;C \begin{multicols}{<++>}<Enter><++><Enter>\end{multicols}<Esc>/usepackage<Enter>o\usepackage{multicol}<Esc>/<++><Enter>"_c4l
autocmd FileType tex inoremap ;v \begin{tcolorbox}<Enter>\begin{verbatim}<Enter>\end{verbatim}<Enter>\end{tcolorbox}<Esc>kO
autocmd FileType tex inoremap ;V \begin{tcolorbox}<Enter>\begin{verbatim}<Enter><++><Enter>\end{verbatim}<Enter>\end{tcolorbox}<Esc>/usepackage<Enter>o\usepackage{tcolorbox}<Esc>/<++><Enter>"_c4l

"HTML Autocommands
autocmd Filetype html,php setlocal tabstop=1 shiftwidth=1 softtabstop=1
autocmd FileType html,php inoremap ;; <Esc>:g/^\s*$/d<Enter>/<++><Enter>"_c4l
autocmd FileType html,php inoremap ;S <!DOCTYPE html><Enter><html><Enter><head><Enter><meta charset="UTF-8"/><Enter><meta name="viewport"<Space>content="width=device-width,initial-scale=1.0"/><Enter><meta<Space>http-equiv="X-UA-Compatible"<Space>content="ie=edge"/><Enter><title><++></title><Enter><link<Space>rel="stylesheet"<Space>href="<++>/css/styles.css"/><Enter></head><Enter><body><Enter><++><Enter></body><Enter></html><Esc>/<++><Enter>"_c4l
autocmd FileType html,php inoremap ;1 <h1></h1><++><Esc>8hi
autocmd FileType html,php inoremap ;2 <h2></h2><++><Esc>8hi
autocmd FileType html,php inoremap ;3 <h3></h3><++><Esc>8hi
autocmd FileType html,php inoremap ;p <p></p><++><Esc>7hi
autocmd FileType html,php inoremap ;B <strong></strong><++><Esc>12hi
autocmd FileType html,php inoremap ;E <em></em><++><Esc>8hi
autocmd FileType html,php inoremap ;I <img src=""<Space>alt="<++>"><++><Esc>$16hi
autocmd FileType html,php inoremap ;b <br><Enter>
autocmd FileType html,php inoremap ;a <a href=""><++></a><++><Esc>13hi
autocmd FileType html,php inoremap ;A <a target="_blank"<Space>href=""><++></a><++><Esc>13hi
autocmd FileType html,php inoremap ;l <ul><Enter><li></li><Enter><++><Enter></ul><Enter><++><Esc>3k$4hi
autocmd FileType html,php inoremap ;L <ol><Enter><li></li><Enter><++><Enter></ol><Enter><++><Esc>3k$4hi
autocmd FileType html,php inoremap ;i <li></li><Enter><++><Esc>k$4hi
autocmd FileType html,php inoremap ;ta <table><Enter><Enter></table><Enter><++><Esc>2ki
autocmd FileType html,php inoremap ;tr <tr><Enter><Enter></tr><Enter><++><Esc>2ki
autocmd FileType html,php inoremap ;th <th></th><Enter><++><Esc>k$4hi
autocmd FileType html,php inoremap ;td <td></td><Enter><++><Esc>k$4hi
autocmd FileType html,php inoremap ;fs <form<Space>action=""<Space>method=""><Enter><Enter><br><Enter><button<Space>type="submit">Submit</button><Enter></form><Enter><++><Esc>4ki
autocmd FileType html,php inoremap ;fl <label<Space>for=""><++></label><Enter><++><Esc>k$13hi
autocmd FileType html,php inoremap ;fi <input<Space>type=""<Space>name="<++>"<Space>id="<++>"/><Enter><++><Esc>k$24hi
autocmd FileType html,php inoremap ;d <div><Enter><Enter></div><++><Esc>ki
autocmd FileType html,php inoremap ;s <span></span><++><Esc>10hi

"CSS Autocommands
autocmd Filetype css setlocal tabstop=1 shiftwidth=1 softtabstop=1
