# Command Completion, use tab twice to use menu select
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select

# Set xterm to 256 color
TERM='xterm-256color'
export TERM

# Prevent .lessshst from being in $HOME
export LESSHISTFILE=-

# Set History information
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
export HISTFILE='/home/balthamer/.zhistory'
export HISTSIZE=5000
export SAVEHIST=5000

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Adds all the ls colors to the environment variables
eval $(dircolors)
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

alias ls='lsd'
alias grep='grep --color=auto'
alias tree='tree -C'
alias ip='ip -c'
alias ll='lsd -lh'
alias la='lsd -lAh'
alias lt='lsd --tree'
alias py='python3'
alias pacman='sudo pacman'
alias tmux='TERM=xterm-256color tmux'
alias clock='while true; do tput clear; date +"%H : %M : %S" | figlet; sleep 1; done'
alias ..='cd ..'
alias mlp='/home/balthamer/Scripts/mlp.sh'
alias chbg='/home/balthamer/Scripts/chbg.sh'
alias pm='pulsemixer'
alias office='libreoffice'
alias cat='bat'
alias mutt='neomutt'
alias xclip='xclip -selection clipboard'

alias work='cd ~/Git/Learning/WGU/Capstone/Task_1'

PS1='%F{red}[%f%F{yellow}%n%f%F{green}@%f%F{blue}%m%f %F{magenta}%1~%f%F{red}]%f '

# Starship prompt
eval "$(starship init zsh)"

# Colored man pages
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Check if system is up-to-date
~/Scripts/update_log.sh
